### ISSUE TITLE
TODO: comandline interface

### ISSUE THREAD

**Issue by Cube707** [Cube707/badges#1]
The interface should consist of these commands:

- [x] `create` a single badge. 
- [ ] `generate` a set of badges at once, from a dataset
- [ ] `check` if a dataset is valid, not jet sure if fthis makes sens
