### ISSUE TITLE
TODO: create API 

### ISSUE THREAD

**Issue by Cube707** [Cube707/badges#2]
the api should consist of functions that a user can use to get the comandline functionalaty directly from within python. So the same functions are required:

- [ ] `create_badge()` for a single badge
- [ ] `generate_badges()` for multiple badges at once
- [ ] `check()` or `validate_dataset()` to validate a dataset
